controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    use_sim_time: true

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    use_sim_time: true
    
    # UPDATED: Names match Waffle URDF/Proto
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    
    # UPDATED: Waffle Physics (0.144m * 2)
    wheel_separation: 0.288
    wheel_radius: 0.033

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true