controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    use_sim_time: true

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    use_sim_time: true
    
    # BELANGRIJK: Deze namen moeten exact matchen met de URDF
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    
    # Settings voor de fysica van de robot
    wheel_separation: 0.160
    wheel_radius: 0.033

    # Odometrie instellingen
    use_stamped_vel: false
    # base_frame_id: base_link  <-- Vaak niet expliciet nodig, defaults zijn meestal goed

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    # We hoeven hier geen joints te specificeren, hij pakt automatisch alles
    # wat hij in de URDF interface vindt.